name: Maz Studio
description: 1인 인디게임 개발사. 1-man Indie Game Development 

sass:
  sass_dir: assets/css/_sass
  style: :compressed

# url: http://nadjetey.github.io

owner:
    name: Maz Studio 
    twitter: #maz_studio
    github: #
    disqus_shortname: #

ga_id: #
ga_username: #

permalink: /:year/:month/:title/
timezone: Africa/Accra

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
